server:
  port: 8089

#mybatis:
#  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    data-username: hotel
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=UTC
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
     restart:
       enabled: true
  freemarker:
    cache: false

