package com.hnist.hotel.dao;

import com.hnist.hotel.pojo.CheckInDO;
import org.springframework.stereotype.Repository;

@Repository
public interface CheckInDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int insert(CheckInDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int insertSelective(CheckInDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    CheckInDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int updateByPrimaryKeySelective(CheckInDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int updateByPrimaryKey(CheckInDO record);
}