package com.hnist.hotel.dao;

import com.hnist.hotel.pojo.HotelDO;
import org.springframework.stereotype.Repository;

@Repository
public interface HotelDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int insert(HotelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int insertSelective(HotelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    HotelDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int updateByPrimaryKeySelective(HotelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int updateByPrimaryKey(HotelDO record);
}