package com.hnist.hotel.dao;

import com.hnist.hotel.pojo.RoomTypeDO;
import org.springframework.stereotype.Repository;

@Repository
public interface RoomTypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int insert(RoomTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int insertSelective(RoomTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    RoomTypeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int updateByPrimaryKeySelective(RoomTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    int updateByPrimaryKey(RoomTypeDO record);
}