package com.hnist.hotel.pojo;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "city_name")
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.hotel_id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "hotel_num")
    private Integer hotelnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.id
     *
     * @return the value of city.id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.id
     *
     * @param id the value for city.id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param cityName the value for city.city_name
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.hotel_id
     *
     * @return the value of city.hotel_id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Integer getHotelnum() {
        return hotelnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.hotel_id
     *
     * @param hotelnum the value for city.hotel_id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setHotelnum(Integer hotelnum) {
        this.hotelnum = hotelnum;
    }
}