package com.hnist.hotel.pojo;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

@Table(name = "hotel")
public class Hotel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.hotel_img
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "hotel_img")
    private String hotelImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.hotel_name
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "hotel_name")
    private String hotelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.city
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "city")
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.phone
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "phone")
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.email
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "email")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.address
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "address")
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.website
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "website")
    private String website;

    @Column(name = "hotel_lowprice")
    private  Integer hotellowprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.create_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.update_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    @Column(name = "update_time")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.id
     *
     * @return the value of hotel.id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.id
     *
     * @param id the value for hotel.id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.hotel_img
     *
     * @return the value of hotel.hotel_img
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getHotelImg() {
        return hotelImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.hotel_img
     *
     * @param hotelImg the value for hotel.hotel_img
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setHotelImg(String hotelImg) {
        this.hotelImg = hotelImg == null ? null : hotelImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.hotel_name
     *
     * @return the value of hotel.hotel_name
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.hotel_name
     *
     * @param hotelName the value for hotel.hotel_name
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.city
     *
     * @return the value of hotel.city
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.city
     *
     * @param city the value for hotel.city
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.phone
     *
     * @return the value of hotel.phone
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.phone
     *
     * @param phone the value for hotel.phone
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.email
     *
     * @return the value of hotel.email
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.email
     *
     * @param email the value for hotel.email
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.address
     *
     * @return the value of hotel.address
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.address
     *
     * @param address the value for hotel.address
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.website
     *
     * @return the value of hotel.website
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.website
     *
     * @param website the value for hotel.website
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.create_time
     *
     * @return the value of hotel.create_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.create_time
     *
     * @param createTime the value for hotel.create_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.update_time
     *
     * @return the value of hotel.update_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.update_time
     *
     * @param updateTime the value for hotel.update_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getHotellowprice() {
        return hotellowprice;
    }

    public void setHotellowprice(Integer hotellowprice) {
        this.hotellowprice = hotellowprice;
    }
}