package com.hnist.hotel.pojo;

import java.util.Date;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.titile
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    private String titile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.ncontent
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    private String ncontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.create_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.titile
     *
     * @return the value of notice.titile
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getTitile() {
        return titile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.titile
     *
     * @param titile the value for notice.titile
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setTitile(String titile) {
        this.titile = titile == null ? null : titile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.ncontent
     *
     * @return the value of notice.ncontent
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getNcontent() {
        return ncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.ncontent
     *
     * @param ncontent the value for notice.ncontent
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setNcontent(String ncontent) {
        this.ncontent = ncontent == null ? null : ncontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.create_time
     *
     * @return the value of notice.create_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.create_time
     *
     * @param createTime the value for notice.create_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}