package com.hnist.hotel.pojo;

import java.util.Date;

public class RoomType {
    private Integer id;
    private String roomType;

    //床的数量
    private Integer bedNumber;

    private String bedSize;
    //
    private Integer window;
    private Date createTime;
    private Date updateTime;
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public String getRoomType() {
        return roomType;
    }


    public void setRoomType(String roomType) {
        this.roomType = roomType == null ? null : roomType.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.price
     *
     * @return the value of room_type.price
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.discount
     *
     * @return the value of room_type.discount
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.area
     *
     * @return the value of room_type.area
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.bed_number
     *
     * @return the value of room_type.bed_number
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Integer getBedNumber() {
        return bedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.bed_number
     *
     * @param bedNumber the value for room_type.bed_number
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setBedNumber(Integer bedNumber) {
        this.bedNumber = bedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.bed_size
     *
     * @return the value of room_type.bed_size
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public String getBedSize() {
        return bedSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.bed_size
     *
     * @param bedSize the value for room_type.bed_size
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setBedSize(String bedSize) {
        this.bedSize = bedSize == null ? null : bedSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.window
     *
     * @return the value of room_type.window
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Integer getWindow() {
        return window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.window
     *
     * @param window the value for room_type.window
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setWindow(Integer window) {
        this.window = window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.create_time
     *
     * @return the value of room_type.create_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.create_time
     *
     * @param createTime the value for room_type.create_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.update_time
     *
     * @return the value of room_type.update_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.update_time
     *
     * @param updateTime the value for room_type.update_time
     *
     * @mbg.generated Tue Dec 10 21:40:46 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}