package com.hnist.hotel.pojo;

import java.util.Date;

public class RoomDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_number
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String roomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.type_id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String roomType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_price
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Double roomPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_discount
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Double roomDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_status
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Byte roomStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.remark
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.create_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.update_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_number
     *
     * @return the value of room.room_number
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_number
     *
     * @param roomNumber the value for room.room_number
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber == null ? null : roomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.type_id
     *
     * @return the value of room.type_id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.type_id
     *
     * @param typeId the value for room.type_id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_type
     *
     * @return the value of room.room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_type
     *
     * @param roomType the value for room.room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setRoomType(String roomType) {
        this.roomType = roomType == null ? null : roomType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_price
     *
     * @return the value of room.room_price
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Double getRoomPrice() {
        return roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_price
     *
     * @param roomPrice the value for room.room_price
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setRoomPrice(Double roomPrice) {
        this.roomPrice = roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_discount
     *
     * @return the value of room.room_discount
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Double getRoomDiscount() {
        return roomDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_discount
     *
     * @param roomDiscount the value for room.room_discount
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setRoomDiscount(Double roomDiscount) {
        this.roomDiscount = roomDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_status
     *
     * @return the value of room.room_status
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Byte getRoomStatus() {
        return roomStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_status
     *
     * @param roomStatus the value for room.room_status
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setRoomStatus(Byte roomStatus) {
        this.roomStatus = roomStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.remark
     *
     * @return the value of room.remark
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.remark
     *
     * @param remark the value for room.remark
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.create_time
     *
     * @return the value of room.create_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.create_time
     *
     * @param createTime the value for room.create_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.update_time
     *
     * @return the value of room.update_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.update_time
     *
     * @param updateTime the value for room.update_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}