package com.hnist.hotel.pojo;

import java.util.Date;

public class RoomTypeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String roomType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.remark
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.price
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.discount
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Double discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.area
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.bed_number
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Integer bedNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.bed_size
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String bedSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.window
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Integer window;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.create_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.update_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.id
     *
     * @return the value of room_type.id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.id
     *
     * @param id the value for room_type.id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.room_type
     *
     * @return the value of room_type.room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.room_type
     *
     * @param roomType the value for room_type.room_type
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setRoomType(String roomType) {
        this.roomType = roomType == null ? null : roomType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.remark
     *
     * @return the value of room_type.remark
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.remark
     *
     * @param remark the value for room_type.remark
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.price
     *
     * @return the value of room_type.price
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.price
     *
     * @param price the value for room_type.price
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.discount
     *
     * @return the value of room_type.discount
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.discount
     *
     * @param discount the value for room_type.discount
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.area
     *
     * @return the value of room_type.area
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.area
     *
     * @param area the value for room_type.area
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.bed_number
     *
     * @return the value of room_type.bed_number
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Integer getBedNumber() {
        return bedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.bed_number
     *
     * @param bedNumber the value for room_type.bed_number
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setBedNumber(Integer bedNumber) {
        this.bedNumber = bedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.bed_size
     *
     * @return the value of room_type.bed_size
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getBedSize() {
        return bedSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.bed_size
     *
     * @param bedSize the value for room_type.bed_size
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setBedSize(String bedSize) {
        this.bedSize = bedSize == null ? null : bedSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.window
     *
     * @return the value of room_type.window
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Integer getWindow() {
        return window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.window
     *
     * @param window the value for room_type.window
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setWindow(Integer window) {
        this.window = window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.create_time
     *
     * @return the value of room_type.create_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.create_time
     *
     * @param createTime the value for room_type.create_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.update_time
     *
     * @return the value of room_type.update_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.update_time
     *
     * @param updateTime the value for room_type.update_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}