package com.hnist.hotel.pojo;

import java.util.Date;

public class WorkerDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.hotel_id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.role
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.username
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.password
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.name
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.gender
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.phone
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.email
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.address
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.create_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.update_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.id
     *
     * @return the value of worker.id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.id
     *
     * @param id the value for worker.id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.hotel_id
     *
     * @return the value of worker.hotel_id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.hotel_id
     *
     * @param hotelId the value for worker.hotel_id
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.role
     *
     * @return the value of worker.role
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.role
     *
     * @param role the value for worker.role
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.username
     *
     * @return the value of worker.username
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.username
     *
     * @param username the value for worker.username
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.password
     *
     * @return the value of worker.password
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.password
     *
     * @param password the value for worker.password
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.name
     *
     * @return the value of worker.name
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.name
     *
     * @param name the value for worker.name
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.gender
     *
     * @return the value of worker.gender
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.gender
     *
     * @param gender the value for worker.gender
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.phone
     *
     * @return the value of worker.phone
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.phone
     *
     * @param phone the value for worker.phone
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.email
     *
     * @return the value of worker.email
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.email
     *
     * @param email the value for worker.email
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.address
     *
     * @return the value of worker.address
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.address
     *
     * @param address the value for worker.address
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.create_time
     *
     * @return the value of worker.create_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.create_time
     *
     * @param createTime the value for worker.create_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.update_time
     *
     * @return the value of worker.update_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.update_time
     *
     * @param updateTime the value for worker.update_time
     *
     * @mbg.generated Tue Dec 10 16:13:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}